[package]
name = "lifetime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "get-first-word"

[[example]]
name = "strtok"

[dependencies]
